# Travis CI Testing file
# This file will be renamed docker-compose.override.yml
# it will override a standard AzuraCast installation.

services:
  cli:
    build:
      context: .
    volumes:
      - ./:/app
    env_file: azuracast.env
    command: /bin/true
  web:
    volumes:
      - ./tests/resources/:/var/azuracast/init_music
