<?php
/**
 * ApiTime
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ApiTime Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiTime implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Api_Time';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'timestamp' => 'int',
'utc_datetime' => 'string',
'utc_date' => 'string',
'utc_time' => 'string',
'utc_json' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'timestamp' => null,
'utc_datetime' => null,
'utc_date' => null,
'utc_time' => null,
'utc_json' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timestamp' => 'timestamp',
'utc_datetime' => 'utc_datetime',
'utc_date' => 'utc_date',
'utc_time' => 'utc_time',
'utc_json' => 'utc_json'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timestamp' => 'setTimestamp',
'utc_datetime' => 'setUtcDatetime',
'utc_date' => 'setUtcDate',
'utc_time' => 'setUtcTime',
'utc_json' => 'setUtcJson'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timestamp' => 'getTimestamp',
'utc_datetime' => 'getUtcDatetime',
'utc_date' => 'getUtcDate',
'utc_time' => 'getUtcTime',
'utc_json' => 'getUtcJson'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['utc_datetime'] = isset($data['utc_datetime']) ? $data['utc_datetime'] : null;
        $this->container['utc_date'] = isset($data['utc_date']) ? $data['utc_date'] : null;
        $this->container['utc_time'] = isset($data['utc_time']) ? $data['utc_time'] : null;
        $this->container['utc_json'] = isset($data['utc_json']) ? $data['utc_json'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timestamp
     *
     * @return int
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param int $timestamp The current UNIX timestamp
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets utc_datetime
     *
     * @return string
     */
    public function getUtcDatetime()
    {
        return $this->container['utc_datetime'];
    }

    /**
     * Sets utc_datetime
     *
     * @param string $utc_datetime utc_datetime
     *
     * @return $this
     */
    public function setUtcDatetime($utc_datetime)
    {
        $this->container['utc_datetime'] = $utc_datetime;

        return $this;
    }

    /**
     * Gets utc_date
     *
     * @return string
     */
    public function getUtcDate()
    {
        return $this->container['utc_date'];
    }

    /**
     * Sets utc_date
     *
     * @param string $utc_date utc_date
     *
     * @return $this
     */
    public function setUtcDate($utc_date)
    {
        $this->container['utc_date'] = $utc_date;

        return $this;
    }

    /**
     * Gets utc_time
     *
     * @return string
     */
    public function getUtcTime()
    {
        return $this->container['utc_time'];
    }

    /**
     * Sets utc_time
     *
     * @param string $utc_time utc_time
     *
     * @return $this
     */
    public function setUtcTime($utc_time)
    {
        $this->container['utc_time'] = $utc_time;

        return $this;
    }

    /**
     * Gets utc_json
     *
     * @return string
     */
    public function getUtcJson()
    {
        return $this->container['utc_json'];
    }

    /**
     * Sets utc_json
     *
     * @param string $utc_json utc_json
     *
     * @return $this
     */
    public function setUtcJson($utc_json)
    {
        $this->container['utc_json'] = $utc_json;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
