<?php
/**
 * ApiStationQueueDetailedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApiStationQueueDetailedTest Class Doc Comment
 *
 * @category    Class
 * @description ApiStationQueueDetailed
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApiStationQueueDetailedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiStationQueueDetailed"
     */
    public function testApiStationQueueDetailed()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "sent_to_autodj"
     */
    public function testPropertySentToAutodj()
    {
    }

    /**
     * Test attribute "is_played"
     */
    public function testPropertyIsPlayed()
    {
    }

    /**
     * Test attribute "autodj_custom_uri"
     */
    public function testPropertyAutodjCustomUri()
    {
    }

    /**
     * Test attribute "log"
     */
    public function testPropertyLog()
    {
    }
}
