<?php
/**
 * ApiStationRemoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApiStationRemoteTest Class Doc Comment
 *
 * @category    Class
 * @description ApiStationRemote
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApiStationRemoteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiStationRemote"
     */
    public function testApiStationRemote()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "is_visible_on_public_pages"
     */
    public function testPropertyIsVisibleOnPublicPages()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "is_editable"
     */
    public function testPropertyIsEditable()
    {
    }

    /**
     * Test attribute "enable_autodj"
     */
    public function testPropertyEnableAutodj()
    {
    }

    /**
     * Test attribute "autodj_format"
     */
    public function testPropertyAutodjFormat()
    {
    }

    /**
     * Test attribute "autodj_bitrate"
     */
    public function testPropertyAutodjBitrate()
    {
    }

    /**
     * Test attribute "custom_listen_url"
     */
    public function testPropertyCustomListenUrl()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "mount"
     */
    public function testPropertyMount()
    {
    }

    /**
     * Test attribute "admin_password"
     */
    public function testPropertyAdminPassword()
    {
    }

    /**
     * Test attribute "source_port"
     */
    public function testPropertySourcePort()
    {
    }

    /**
     * Test attribute "source_mount"
     */
    public function testPropertySourceMount()
    {
    }

    /**
     * Test attribute "source_username"
     */
    public function testPropertySourceUsername()
    {
    }

    /**
     * Test attribute "source_password"
     */
    public function testPropertySourcePassword()
    {
    }

    /**
     * Test attribute "is_public"
     */
    public function testPropertyIsPublic()
    {
    }

    /**
     * Test attribute "listeners_unique"
     */
    public function testPropertyListenersUnique()
    {
    }

    /**
     * Test attribute "listeners_total"
     */
    public function testPropertyListenersTotal()
    {
    }
}
