<?php
/**
 * SettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Settings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Settings"
     */
    public function testSettings()
    {
    }

    /**
     * Test attribute "app_unique_identifier"
     */
    public function testPropertyAppUniqueIdentifier()
    {
    }

    /**
     * Test attribute "base_url"
     */
    public function testPropertyBaseUrl()
    {
    }

    /**
     * Test attribute "instance_name"
     */
    public function testPropertyInstanceName()
    {
    }

    /**
     * Test attribute "prefer_browser_url"
     */
    public function testPropertyPreferBrowserUrl()
    {
    }

    /**
     * Test attribute "use_radio_proxy"
     */
    public function testPropertyUseRadioProxy()
    {
    }

    /**
     * Test attribute "history_keep_days"
     */
    public function testPropertyHistoryKeepDays()
    {
    }

    /**
     * Test attribute "always_use_ssl"
     */
    public function testPropertyAlwaysUseSsl()
    {
    }

    /**
     * Test attribute "api_access_control"
     */
    public function testPropertyApiAccessControl()
    {
    }

    /**
     * Test attribute "enable_static_nowplaying"
     */
    public function testPropertyEnableStaticNowplaying()
    {
    }

    /**
     * Test attribute "analytics"
     */
    public function testPropertyAnalytics()
    {
    }

    /**
     * Test attribute "check_for_updates"
     */
    public function testPropertyCheckForUpdates()
    {
    }

    /**
     * Test attribute "update_results"
     */
    public function testPropertyUpdateResults()
    {
    }

    /**
     * Test attribute "update_last_run"
     */
    public function testPropertyUpdateLastRun()
    {
    }

    /**
     * Test attribute "public_theme"
     */
    public function testPropertyPublicTheme()
    {
    }

    /**
     * Test attribute "hide_album_art"
     */
    public function testPropertyHideAlbumArt()
    {
    }

    /**
     * Test attribute "homepage_redirect_url"
     */
    public function testPropertyHomepageRedirectUrl()
    {
    }

    /**
     * Test attribute "default_album_art_url"
     */
    public function testPropertyDefaultAlbumArtUrl()
    {
    }

    /**
     * Test attribute "use_external_album_art_when_processing_media"
     */
    public function testPropertyUseExternalAlbumArtWhenProcessingMedia()
    {
    }

    /**
     * Test attribute "use_external_album_art_in_apis"
     */
    public function testPropertyUseExternalAlbumArtInApis()
    {
    }

    /**
     * Test attribute "last_fm_api_key"
     */
    public function testPropertyLastFmApiKey()
    {
    }

    /**
     * Test attribute "hide_product_name"
     */
    public function testPropertyHideProductName()
    {
    }

    /**
     * Test attribute "public_custom_css"
     */
    public function testPropertyPublicCustomCss()
    {
    }

    /**
     * Test attribute "public_custom_js"
     */
    public function testPropertyPublicCustomJs()
    {
    }

    /**
     * Test attribute "internal_custom_css"
     */
    public function testPropertyInternalCustomCss()
    {
    }

    /**
     * Test attribute "backup_enabled"
     */
    public function testPropertyBackupEnabled()
    {
    }

    /**
     * Test attribute "backup_time_code"
     */
    public function testPropertyBackupTimeCode()
    {
    }

    /**
     * Test attribute "backup_exclude_media"
     */
    public function testPropertyBackupExcludeMedia()
    {
    }

    /**
     * Test attribute "backup_keep_copies"
     */
    public function testPropertyBackupKeepCopies()
    {
    }

    /**
     * Test attribute "backup_storage_location"
     */
    public function testPropertyBackupStorageLocation()
    {
    }

    /**
     * Test attribute "backup_format"
     */
    public function testPropertyBackupFormat()
    {
    }

    /**
     * Test attribute "backup_last_run"
     */
    public function testPropertyBackupLastRun()
    {
    }

    /**
     * Test attribute "backup_last_output"
     */
    public function testPropertyBackupLastOutput()
    {
    }

    /**
     * Test attribute "setup_complete_time"
     */
    public function testPropertySetupCompleteTime()
    {
    }

    /**
     * Test attribute "sync_disabled"
     */
    public function testPropertySyncDisabled()
    {
    }

    /**
     * Test attribute "sync_last_run"
     */
    public function testPropertySyncLastRun()
    {
    }

    /**
     * Test attribute "external_ip"
     */
    public function testPropertyExternalIp()
    {
    }

    /**
     * Test attribute "geolite_license_key"
     */
    public function testPropertyGeoliteLicenseKey()
    {
    }

    /**
     * Test attribute "geolite_last_run"
     */
    public function testPropertyGeoliteLastRun()
    {
    }

    /**
     * Test attribute "enable_advanced_features"
     */
    public function testPropertyEnableAdvancedFeatures()
    {
    }

    /**
     * Test attribute "mail_enabled"
     */
    public function testPropertyMailEnabled()
    {
    }

    /**
     * Test attribute "mail_sender_name"
     */
    public function testPropertyMailSenderName()
    {
    }

    /**
     * Test attribute "mail_sender_email"
     */
    public function testPropertyMailSenderEmail()
    {
    }

    /**
     * Test attribute "mail_smtp_host"
     */
    public function testPropertyMailSmtpHost()
    {
    }

    /**
     * Test attribute "mail_smtp_port"
     */
    public function testPropertyMailSmtpPort()
    {
    }

    /**
     * Test attribute "mail_smtp_username"
     */
    public function testPropertyMailSmtpUsername()
    {
    }

    /**
     * Test attribute "mail_smtp_password"
     */
    public function testPropertyMailSmtpPassword()
    {
    }

    /**
     * Test attribute "mail_smtp_secure"
     */
    public function testPropertyMailSmtpSecure()
    {
    }

    /**
     * Test attribute "avatar_service"
     */
    public function testPropertyAvatarService()
    {
    }

    /**
     * Test attribute "avatar_default_url"
     */
    public function testPropertyAvatarDefaultUrl()
    {
    }

    /**
     * Test attribute "acme_email"
     */
    public function testPropertyAcmeEmail()
    {
    }

    /**
     * Test attribute "acme_domains"
     */
    public function testPropertyAcmeDomains()
    {
    }
}
