<?php
/**
 * StationPlaylistTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StationPlaylistTest Class Doc Comment
 *
 * @category    Class
 * @description StationPlaylist
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationPlaylistTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationPlaylist"
     */
    public function testStationPlaylist()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "remote_url"
     */
    public function testPropertyRemoteUrl()
    {
    }

    /**
     * Test attribute "remote_type"
     */
    public function testPropertyRemoteType()
    {
    }

    /**
     * Test attribute "remote_buffer"
     */
    public function testPropertyRemoteBuffer()
    {
    }

    /**
     * Test attribute "is_enabled"
     */
    public function testPropertyIsEnabled()
    {
    }

    /**
     * Test attribute "is_jingle"
     */
    public function testPropertyIsJingle()
    {
    }

    /**
     * Test attribute "play_per_songs"
     */
    public function testPropertyPlayPerSongs()
    {
    }

    /**
     * Test attribute "play_per_minutes"
     */
    public function testPropertyPlayPerMinutes()
    {
    }

    /**
     * Test attribute "play_per_hour_minute"
     */
    public function testPropertyPlayPerHourMinute()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "include_in_requests"
     */
    public function testPropertyIncludeInRequests()
    {
    }

    /**
     * Test attribute "include_in_on_demand"
     */
    public function testPropertyIncludeInOnDemand()
    {
    }

    /**
     * Test attribute "backend_options"
     */
    public function testPropertyBackendOptions()
    {
    }

    /**
     * Test attribute "avoid_duplicates"
     */
    public function testPropertyAvoidDuplicates()
    {
    }

    /**
     * Test attribute "schedule_items"
     */
    public function testPropertyScheduleItems()
    {
    }
}
