<?php
/**
 * StationMountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StationMountTest Class Doc Comment
 *
 * @category    Class
 * @description StationMount
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationMountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationMount"
     */
    public function testStationMount()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "is_visible_on_public_pages"
     */
    public function testPropertyIsVisibleOnPublicPages()
    {
    }

    /**
     * Test attribute "is_default"
     */
    public function testPropertyIsDefault()
    {
    }

    /**
     * Test attribute "is_public"
     */
    public function testPropertyIsPublic()
    {
    }

    /**
     * Test attribute "fallback_mount"
     */
    public function testPropertyFallbackMount()
    {
    }

    /**
     * Test attribute "relay_url"
     */
    public function testPropertyRelayUrl()
    {
    }

    /**
     * Test attribute "authhash"
     */
    public function testPropertyAuthhash()
    {
    }

    /**
     * Test attribute "max_listener_duration"
     */
    public function testPropertyMaxListenerDuration()
    {
    }

    /**
     * Test attribute "enable_autodj"
     */
    public function testPropertyEnableAutodj()
    {
    }

    /**
     * Test attribute "autodj_format"
     */
    public function testPropertyAutodjFormat()
    {
    }

    /**
     * Test attribute "autodj_bitrate"
     */
    public function testPropertyAutodjBitrate()
    {
    }

    /**
     * Test attribute "custom_listen_url"
     */
    public function testPropertyCustomListenUrl()
    {
    }

    /**
     * Test attribute "frontend_config"
     */
    public function testPropertyFrontendConfig()
    {
    }

    /**
     * Test attribute "listeners_unique"
     */
    public function testPropertyListenersUnique()
    {
    }

    /**
     * Test attribute "listeners_total"
     */
    public function testPropertyListenersTotal()
    {
    }
}
