<?php
/**
 * StationStreamerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StationStreamerTest Class Doc Comment
 *
 * @category    Class
 * @description Station streamers (DJ accounts) allowed to broadcast to a station.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationStreamerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationStreamer"
     */
    public function testStationStreamer()
    {
    }

    /**
     * Test attribute "streamer_username"
     */
    public function testPropertyStreamerUsername()
    {
    }

    /**
     * Test attribute "streamer_password"
     */
    public function testPropertyStreamerPassword()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "enforce_schedule"
     */
    public function testPropertyEnforceSchedule()
    {
    }

    /**
     * Test attribute "reactivate_at"
     */
    public function testPropertyReactivateAt()
    {
    }

    /**
     * Test attribute "schedule_items"
     */
    public function testPropertyScheduleItems()
    {
    }
}
