<?php
/**
 * StationMediaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AzuraCast
 *
 * AzuraCast is a standalone, turnkey web radio management tool. Radio stations hosted by AzuraCast expose a public API for viewing now playing data, making requests and more.
 *
 * OpenAPI spec version: 0.17.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StationMediaTest Class Doc Comment
 *
 * @category    Class
 * @description StationMedia
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StationMediaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StationMedia"
     */
    public function testStationMedia()
    {
    }

    /**
     * Test attribute "song_id"
     */
    public function testPropertySongId()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "artist"
     */
    public function testPropertyArtist()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "unique_id"
     */
    public function testPropertyUniqueId()
    {
    }

    /**
     * Test attribute "album"
     */
    public function testPropertyAlbum()
    {
    }

    /**
     * Test attribute "genre"
     */
    public function testPropertyGenre()
    {
    }

    /**
     * Test attribute "lyrics"
     */
    public function testPropertyLyrics()
    {
    }

    /**
     * Test attribute "isrc"
     */
    public function testPropertyIsrc()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "length_text"
     */
    public function testPropertyLengthText()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "mtime"
     */
    public function testPropertyMtime()
    {
    }

    /**
     * Test attribute "amplify"
     */
    public function testPropertyAmplify()
    {
    }

    /**
     * Test attribute "fade_overlap"
     */
    public function testPropertyFadeOverlap()
    {
    }

    /**
     * Test attribute "fade_in"
     */
    public function testPropertyFadeIn()
    {
    }

    /**
     * Test attribute "fade_out"
     */
    public function testPropertyFadeOut()
    {
    }

    /**
     * Test attribute "cue_in"
     */
    public function testPropertyCueIn()
    {
    }

    /**
     * Test attribute "cue_out"
     */
    public function testPropertyCueOut()
    {
    }

    /**
     * Test attribute "art_updated_at"
     */
    public function testPropertyArtUpdatedAt()
    {
    }

    /**
     * Test attribute "playlists"
     */
    public function testPropertyPlaylists()
    {
    }
}
